import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { createServerClient } from '@supabase/ssr';
import { cookies } from 'next/headers';
import { computeNextAction, computePriority, sanitizeQuotationForCustomer } from '@/lib/quotation-helpers';
import { sendQuotationReceivedEmails } from '@/lib/quotation-emails';
import { logQuotationEvent } from '@/lib/quotation-helpers';

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  { auth: { autoRefreshToken: false, persistSession: false } }
);

// ─── POST /api/quotations — Submit RFQ ──────────────────────────────────────
export async function POST(request: Request) {
  try {
    const body = await request.json();
    const {
      product_id, product_name, quantity,
      specifications, delivery_location, customer_notes,
      customer_name, customer_email, customer_phone,
    } = body;

    // Basic validation
    if (!customer_name?.trim()) return NextResponse.json({ error: 'Customer name is required' }, { status: 400 });
    if (!customer_email?.trim()) return NextResponse.json({ error: 'Customer email is required' }, { status: 400 });
    if (!customer_phone?.trim()) return NextResponse.json({ error: 'Customer phone is required' }, { status: 400 });
    if (!product_name?.trim()) return NextResponse.json({ error: 'Product name is required' }, { status: 400 });
    if (!delivery_location?.state) return NextResponse.json({ error: 'Delivery state is required' }, { status: 400 });

    // Get logged-in user if any
    let userId: string | null = null;
    try {
      const cookieStore = await cookies();
      const supabaseClient = createServerClient(
        process.env.NEXT_PUBLIC_SUPABASE_URL!,
        process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
        { cookies: { getAll: () => cookieStore.getAll() } }
      );
      const { data: { user } } = await supabaseClient.auth.getUser();
      if (user) userId = user.id;
    } catch { /* guest submission — userId stays null */ }

    const nextAction = computeNextAction({ status: 'REQUESTED', supplier_fulfillment_status: 'NOT_SUBMITTED', is_exception: false, fulfillment_blocked: false });

    // Reference and access_token are generated by DB defaults (sequence + gen_random_uuid)
    const { data: quotation, error } = await supabaseAdmin
      .from('quotations')
      .insert({
        user_id: userId,
        product_id: product_id || null,
        product_name: product_name.trim(),
        quantity: Math.max(1, parseInt(quantity) || 1),
        specifications: specifications || {},
        delivery_location: delivery_location || {},
        customer_notes: customer_notes?.trim() || null,
        customer_name: customer_name.trim(),
        customer_email: customer_email.trim().toLowerCase(),
        customer_phone: customer_phone.trim(),
        status: 'REQUESTED',
        priority: 'NORMAL',
        next_action: nextAction,
      })
      .select()
      .single();

    if (error || !quotation) {
      console.error('Failed to create quotation:', error);
      return NextResponse.json({ error: 'Failed to submit quotation request' }, { status: 500 });
    }

    // Log timeline event
    await logQuotationEvent(quotation.id, 'QUOTATION_SUBMITTED', 'Customer submitted quotation request', 'customer');

    // Send emails (don't block response on email success)
    sendQuotationReceivedEmails(quotation).catch(err =>
      console.error('Failed to send quotation received emails:', err)
    );

    // Return safe data: include access_token so guest can bookmark the link
    return NextResponse.json({
      success: true,
      quotation: {
        id: quotation.id,
        reference: quotation.reference,
        access_token: quotation.access_token, // Safe to return on creation only
        status: quotation.status,
        status_label: 'Reviewing Your Request',
      }
    }, { status: 201 });

  } catch (err: any) {
    console.error('Error in POST /api/quotations:', err);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

// ─── GET /api/quotations — List own quotations ───────────────────────────────
export async function GET(request: Request) {
  try {
    const cookieStore = await cookies();
    const supabaseClient = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      { cookies: { getAll: () => cookieStore.getAll() } }
    );
    const { data: { user } } = await supabaseClient.auth.getUser();
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const { data: quotations, error } = await supabaseAdmin
      .from('quotations')
      .select('id, reference, product_name, quantity, status, customer_total, quote_valid_until, created_at, quote_accepted_at, payment_status, converted_order_id')
      .eq('user_id', user.id)
      .order('created_at', { ascending: false });

    if (error) return NextResponse.json({ error: 'Failed to fetch quotations' }, { status: 500 });

    const safe = (quotations || []).map(q => ({
      ...q,
      status_label: (() => {
        const labels: Record<string, string> = {
          REQUESTED: 'Reviewing Your Request',
          SUPPLIER_QUOTE_REQUESTED: 'Checking Availability',
          SUPPLIER_RESPONSE_RECEIVED: 'Preparing Your Quote',
          SUPPLIER_SPEC_ISSUE: 'Checking Specifications',
          QUOTE_BEING_PREPARED: 'Preparing Your Quote',
          QUOTE_SENT: 'Quote Ready — Action Required',
          QUOTE_VIEWED: 'Quote Ready — Action Required',
          QUOTE_ACCEPTED: 'Accepted — Please Pay',
          QUOTE_DECLINED: 'Declined',
          QUOTE_EXPIRED: 'Expired',
          PAYMENT_PENDING: 'Payment Processing',
          PAID: 'Paid — In Progress',
          CONVERTED_TO_ORDER: 'Order Created',
        };
        return labels[q.status] || q.status;
      })(),
    }));

    return NextResponse.json({ quotations: safe });
  } catch (err: any) {
    console.error('Error in GET /api/quotations:', err);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
